export const db = "main-stackflow"
export const questionCollection = "questions"
export const anserCollection = "answers"
export const commentCollection = "comments"
export const voteCollection = "votes"
export const questionAttachmentBucket = "question-attachement"